export type Artwork = { id: string; title: string; medium: string; src: string; alt: string; };

export const artwork: Artwork[] = [
  { id: "work-1", title: "Fine-line rose oval", medium: "Tattoo flash, floral linework", alt: "Fine-line rose oval by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-1.webp" },
  { id: "work-2", title: "Peony stem study", medium: "Fine-line botanical drawing", alt: "Peony stem study by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-2.webp" },
  { id: "work-3", title: "Single swallow", medium: "Minimal tattoo study", alt: "Single swallow by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-3.webp" },
  { id: "work-4", title: "Garden sprig", medium: "Floral fine-line flash", alt: "Garden sprig by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-4.webp" },
  { id: "work-5", title: "Thorned bloom", medium: "Botanical tattoo flash", alt: "Thorned bloom by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-5.webp" },
  { id: "work-6", title: "Bud stem", medium: "Fine-line stem study", alt: "Bud stem by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-6.webp" },
  { id: "work-7", title: "Ornamental flower", medium: "Tattoo flash, floral", alt: "Ornamental flower by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-7.webp" },
  { id: "work-8", title: "Flash composition sheet", medium: "Fine-line botanical studies", alt: "Flash composition sheet by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-8.webp" },
  { id: "work-9", title: "Iris and daffodil", medium: "Gouache floral painting", alt: "Iris and daffodil by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-9.webp" },
  { id: "work-10", title: "Close iris detail", medium: "Gouache floral detail", alt: "Close iris detail by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-10.webp" },
  { id: "work-11", title: "Blue flash sheet", medium: "Tattoo flash, blue-black ink", alt: "Blue flash sheet by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-11.webp" },
  { id: "work-12", title: "Tiger head", medium: "Illustrative tattoo flash", alt: "Tiger head by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-12.webp" },
  { id: "work-13", title: "Bramble and moth", medium: "Fine-line floral tattoo", alt: "Bramble and moth by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-13.webp" },
  { id: "work-14", title: "Peony and dragonfly", medium: "Fine-line floral tattoo", alt: "Peony and dragonfly by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-14.webp" },
  { id: "work-15", title: "Skull study", medium: "Fine-line tattoo flash", alt: "Skull study by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-15.webp" },
  { id: "work-16", title: "Butterfly sheet", medium: "Fine-line tattoo flash", alt: "Butterfly sheet by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-16.webp" },
  { id: "work-17", title: "Dove study", medium: "Illustrative tattoo flash", alt: "Dove study by an Edinburgh-based painter and tattoo artist", src: "https://raw.githubusercontent.com/MusseJusse/portfolio-new/master/client/artwork/work-17.webp" },
];
